name: Devloper Tip
title: Add new Developer Tip
description: Add a tech message to the OpenSource API
labels: ["dev-tip"]
body:
  - type: textarea
    id: message
    attributes:
      label: Tip
      description: Add your message you want to include in the API.
    validations:
      required: true
