name: 🏆 Testimonial
title: New Testimonial
description: Make a testimonial for the LinkFree user
labels: ["dev"]
body:
  - type: input
    id: title
    attributes:
      label: Title
      description: Please provide a title for the testimonial
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Dev Message
      description: Add your message which you want to add to the API
    validations:
      required: true
