name: 🏆 Dev Message
title: New Message
description: Add a tech message to the OpenSource API
labels: ["dev"]
body:
  - type: textarea
    id: message
    attributes:
      label: Dev Message
      description: Add your message which you want to add to the API
    validations:
      required: true
