on:
  push:
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
#       - run: echo 1 ${{github.event_name}}
#       - run: echo 2 ${{github.sha}}   
#       - run: echo 3 ${{github.ref}}   
      - run: echo 4 ${{fromJSON(github.event.description)}}   
#       - run: echo 5 ${{github.actor}}   
#       - run: echo 6 ${{github.job}}   
#       - run: echo 7 ${{github.repository}}   
