on:
  push:
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get the version
        run: echo ${{github.event_name}}
      - run: echo ${{github.sha}}   
      - run: echo ${{github.ref}}   
      - run: echo ${{github.event}}   
      - run: echo ${{github.actor}}   
      - run: echo ${{github.job}}   
      - run: echo ${{github.repository}}   
